[project]
name = "models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shaxina", email = "shaxina1106zz@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "dotenv>=0.9.9",
]

[project.scripts]
models = "models:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
